name: markets

services:
    airflow:
        build:
          context: .
          dockerfile: dockerfile/airflow/Dockerfile
        depends_on: 
            - db
        env_file:
          - .env
        volumes:
            - ./root:/root
            - ./datalake:/project/datalake
            - ./dockerfile:/project/dockerfile
            - ./airflow:/project/airflow
        ports:
            - "8080:8080"
        stdin_open: true
        tty: true
        command: bash -c "airflow standalone"
        user: 50000:0
    db:
        image: postgres
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
          - 5432:5432
        volumes:
            - db:/var/lib/postgresql/data
            - ./root:/root
            - ./datalake:/datalake

volumes:
    db:
    airflow:
